---
- hosts: localhost
  connection: local
  gather_facts: no

  vars:
    k8s_kubeconfig: ~/.kube/config
    k8s_manifests_base_dir: k8s-manifests/
    k8s_manifests:
      - namespaces
      - nginx-ingress
      - test

  roles:
    - role: geerlingguy.k8s_manifests
